server.port: 8081

spring:
  kafka:
    consumer:
      group-id: myGroup
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      name: wikimedia_recentchange

  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:${DB_MYSQL_PORT}/wikimedia
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
